apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-signup-config
data:
  DJANGO_ENVIRONMENT: "{{ .Values.djangoEnvironment }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-signup-secrets
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "{{ .Values.djangoSecretKey  }}"
  DJANGO_ADMIN_EMAIL: "{{ .Values.djangoAdminEmail }}"
  DJANGO_ADMIN_USERNAME: "{{ .Values.djangoAdminUsername }}"
  DJANGO_SUPERUSER_PASSWORD:  "{{ .Values.djangoAdminPassword }}"
