apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            timeoutSeconds: 5
            httpGet:
              path: /accounts/login/
              port: 8000
          readinessProbe:
            timeoutSeconds: 5
            httpGet:
              path: /accounts/login/
              port: 8000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: DJANGO_DB_HOST
            value: {{ include "chart.mariadb.fullname" . }}
          - name: DJANGO_DB_PORT
            value: "3306"
          - name: DJANGO_DB_NAME
            value: {{ .Values.mariadb.auth.database }}
          - name: DJANGO_DB_USER
            value: {{ .Values.mariadb.auth.username }}
          - name: DJANGO_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "chart.mariadb.fullname" . }}
                key: mariadb-password
          envFrom:
          - secretRef:
              name: {{ .Release.Name }}-signup-secrets
          - configMapRef:
              name: {{ .Release.Name }}-signup-config
      initContainers:
      - name: init-wait-db
        image: busybox:1.31
        command: ['sh', '-c', 'echo -e "Checking for the availability of MariaDB Server deployment"; while ! nc -z {{ .Release.Name }}-mariadb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local 3306; do sleep 1; printf "-"; done; echo -e "  >> DB Server has started";']
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
