image:
  repository: signupsheet
  pullPolicy: Never
  tag: "latest"

djangoEnvironment: "production"
djangoAdminUsername: "test@test.test"
djangoAdminPassword: "test"
djangoAdminEmail: "test@test.test"
djangoSecretKey: "d&@x3^%(!lgtv-ir=z&ade9vbyw+g4m5#b$^7wb)&5#q_j-7k@"
djangoEmailBackend: "django.core.mail.backends.console.EmailBackend"
djangoEmailHost: ""
djangoEmailPort: ""
djangoEmailUser: ""
djangoEmailPassword: ""
djangoEmailDefaultFrom: "staffsheet@fnf.org"
djangoTrustedOrigin: "https://mydomain.com"

mariadb:
  auth:
    database: signup
    username: signupuser
    password: "test"
    rootPassword: "test"
