apiVersion: v1
kind: ConfigMap
metadata:
  name: signup-config
data:
  django_admin_email: test@test.test
---
apiVersion: v1
kind: Secret
metadata:
  name: django-admin
type: kubernetes.io/basic-auth
stringData:
  username: test
  password: test
---
apiVersion: v1
kind: Service
metadata:
  name: signup
spec:
  selector:
    app: signup
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: signup-deployment
  labels:
    app: signup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signup
  template:
    metadata:
      labels:
        app: signup
    spec:
      containers:
      - name: signup
        image: signup:latest
        imagePullPolicy: Never
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: django-admin
              key: username
        - name: DJANGO_SUPERUSER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: django-admin
              key: password
        - name: DJANGO_ADMIN_EMAIL
          valueFrom:
            configMapKeyRef:
              name: signup-config
              key: django_admin_email
