---
apiVersion: v1
kind: Service
metadata:
  name: signup
spec:
  selector:
    app: signup
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: signup-deployment
  labels:
    app: signup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signup
  template:
    metadata:
      labels:
        app: signup
    spec:
      containers:
      - name: signup
        image: signup:latest
        imagePullPolicy: Never
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: signup-config
        env:
        - name: DJANGO_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: django-admin
              key: django-admin-username
        - name: DJANGO_SUPERUSER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: django-admin
              key: django-admin-password
        - name: DJANGO_ADMIN_EMAIL
          valueFrom:
            secretKeyRef:
              name: django-admin
              key: django-admin-email
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-admin
              key: django-secret-key
        - name: DJANGO_DB_USER
          value: test
        - name: DJANGO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-admin
              key: mariadb-password
        - name: DJANGO_DB_NAME
          value: signup
        - name: DJANGO_DB_HOST
          value: maria-mariadb
        - name: DJANGO_DB_PORT
          value: "3306"
