
replicaCount: 1

image:
  repository: signup
  pullPolicy: Never
  tag: "latest"

service:
  type: NodePort
  port: 8000

auth:
  django-debug: "True"
  django-admin-username: "test" 
  django-admin-password: "test"
  django-admin-email: "test@test.test"
  django-secret-key: 'local-dev-not-a-secrety'
  db-type: "mariadb"
  db-username: "signupuser"
  db-schema: "signup" 

resources: 
  requests:
    cpu: 500m
    memory: 500Mi

mariadb:
  architecture: standalone
  auth:
    rootPassword: test
    password: test
    replicationPassword: test
  secondary:
    replicaCount: 2
    